import { FootballPlayer } from '../types';

export const POPULAR_PLAYERS: FootballPlayer[] = [
  { "name": "Lionel Messi", "position": "RW" },
  { "name": "Cristiano Ronaldo", "position": "ST" },
  { "name": "Kylian Mbappé", "position": "ST/LW" },
  { "name": "Erling Haaland", "position": "ST" },
  { "name": "Vinícius Júnior", "position": "LW" },
  { "name": "Jude Bellingham", "position": "CM" },
  { "name": "Mohamed Salah", "position": "RW" },
  { "name": "Harry Kane", "position": "ST" },
  { "name": "Robert Lewandowski", "position": "ST" },
  { "name": "Lamine Yamal", "position": "RW" },
  { "name": "Rodri", "position": "DM" },
  { "name": "Kevin De Bruyne", "position": "CM" },
  { "name": "Jamal Musiala", "position": "AM" },
  { "name": "Pedri", "position": "CM" },
  { "name": "Bukayo Saka", "position": "RW" },
  { "name": "Phil Foden", "position": "AM" },
  { "name": "Cole Palmer", "position": "AM/RW" },
  { "name": "Florian Wirtz", "position": "AM" },
  { "name": "Ousmane Dembélé", "position": "RW" },
  { "name": "Khvicha Kvaratskhelia", "position": "LW" },
  { "name": "Lautaro Martínez", "position": "ST" },
  { "name": "Julián Álvarez", "position": "ST" },
  { "name": "Raphinha", "position": "RW" },
  { "name": "Bruno Fernandes", "position": "AM" },
  { "name": "Bernardo Silva", "position": "CM/RW" },
  { "name": "Martin Ødegaard", "position": "AM" },
  { "name": "Declan Rice", "position": "DM" },
  { "name": "Federico Valverde", "position": "CM" },
  { "name": "Aurélien Tchouaméni", "position": "DM" },
  { "name": "Eduardo Camavinga", "position": "CM" },
  { "name": "Gavi", "position": "CM" },
  { "name": "Frenkie de Jong", "position": "CM" },
  { "name": "João Neves", "position": "CM" },
  { "name": "João Félix", "position": "FW" },
  { "name": "Victor Osimhen", "position": "ST" },
  { "name": "Alexander Isak", "position": "ST" },
  { "name": "Viktor Gyökeres", "position": "ST" },
  { "name": "Benjamin Šeško", "position": "ST" },
  { "name": "Nico Williams", "position": "LW" },
  { "name": "Rafael Leão", "position": "LW" },
  { "name": "João Cancelo", "position": "RB/LB" },
  { "name": "Achraf Hakimi", "position": "RB" },
  { "name": "Alphonso Davies", "position": "LB" },
  { "name": "Trent Alexander-Arnold", "position": "RB" },
  { "name": "Virgil van Dijk", "position": "CB" },
  { "name": "Rúben Dias", "position": "CB" },
  { "name": "William Saliba", "position": "CB" },
  { "name": "Gabriel Magalhães", "position": "CB" },
  { "name": "Antonio Rüdiger", "position": "CB" },
  { "name": "Éder Militão", "position": "CB" },
  { "name": "Marquinhos", "position": "CB" },
  { "name": "Alessandro Bastoni", "position": "CB" },
  { "name": "Ronald Araújo", "position": "CB" },
  { "name": "Dayot Upamecano", "position": "CB" },
  { "name": "Pau Cubarsí", "position": "CB" },
  { "name": "Gianluigi Donnarumma", "position": "GK" },
  { "name": "Thibaut Courtois", "position": "GK" },
  { "name": "Alisson Becker", "position": "GK" },
  { "name": "Ederson", "position": "GK" },
  { "name": "Mike Maignan", "position": "GK" },
  { "name": "Jan Oblak", "position": "GK" },
  { "name": "Emiliano Martínez", "position": "GK" },
  { "name": "Manuel Neuer", "position": "GK" },
  { "name": "Wojciech Szczęsny", "position": "GK" },
  { "name": "Marc-André ter Stegen", "position": "GK" },
  { "name": "Son Heung-min", "position": "LW" },
  { "name": "Leroy Sané", "position": "RW" },
  { "name": "Serge Gnabry", "position": "RW" },
  { "name": "Kingsley Coman", "position": "LW" },
  { "name": "Kai Havertz", "position": "ST" },
  { "name": "Dominik Szoboszlai", "position": "CM" },
  { "name": "Alexis Mac Allister", "position": "CM" },
  { "name": "Enzo Fernández", "position": "CM" },
  { "name": "Moisés Caicedo", "position": "DM" },
  { "name": "Alexis Sánchez", "position": "FW" },
  { "name": "Romelu Lukaku", "position": "ST" },
  { "name": "Marcus Rashford", "position": "LW" },
  { "name": "Alejandro Garnacho", "position": "LW" },
  { "name": "Kobbie Mainoo", "position": "CM" },
  { "name": "Mason Mount", "position": "AM" },
  { "name": "Jack Grealish", "position": "LW" },
  { "name": "Jérémy Doku", "position": "LW" },
  { "name": "Savinho", "position": "RW" },
  { "name": "Omar Marmoush", "position": "FW" },
  { "name": "Ivan Toney", "position": "ST" },
  { "name": "Ollie Watkins", "position": "ST" },
  { "name": "Darwin Núñez", "position": "ST" },
  { "name": "Luis Díaz", "position": "LW" },
  { "name": "Cody Gakpo", "position": "LW" },
  { "name": "Antony", "position": "RW" },
  { "name": "Antoine Griezmann", "position": "FW" },
  { "name": "Memphis Depay", "position": "FW" },
  { "name": "Christian Pulisic", "position": "RW" },
  { "name": "Hakan Çalhanoğlu", "position": "CM" },
  { "name": "Nicolò Barella", "position": "CM" },
  { "name": "Dusan Vlahović", "position": "ST" },
  { "name": "Xavi Simons", "position": "AM" },
  { "name": "Dani Olmo", "position": "AM" },
  { "name": "Dani Carvajal", "position": "RB" },
  { "name": "Ferland Mendy", "position": "LB" },
  { "name": "Alejandro Balde", "position": "LB" },
  { "name": "Jules Koundé", "position": "RB/CB" },
  { "name": "Iñigo Martínez", "position": "CB" },
  { "name": "Pau Torres", "position": "CB" },
  { "name": "Aymeric Laporte", "position": "CB" },
  { "name": "João Palhinha", "position": "DM" },
  { "name": "Sandro Tonali", "position": "CM" },
  { "name": "Nicolò Fagioli", "position": "CM" },
  { "name": "Teun Koopmeiners", "position": "CM" },
  { "name": "Manuel Locatelli", "position": "DM" },
  { "name": "Adrien Rabiot", "position": "CM" },
  { "name": "İlkay Gündoğan", "position": "CM" },
  { "name": "Thomas Müller", "position": "AM" },
  { "name": "Joshua Kimmich", "position": "DM/RB" },
  { "name": "Leon Goretzka", "position": "CM" },
  { "name": "Sergej Milinković-Savić", "position": "CM" },
  { "name": "Marcelo Brozović", "position": "DM" },
  { "name": "N'Golo Kanté", "position": "DM" },
  { "name": "Casemiro", "position": "DM" },
  { "name": "Luka Modrić", "position": "CM" },
  { "name": "Luka Sučić", "position": "CM" },
  { "name": "Luka Jović", "position": "ST" },
  { "name": "Youssef En-Nesyri", "position": "ST" },
  { "name": "Hakim Ziyech", "position": "RW" },
  { "name": "Sofyan Amrabat", "position": "DM" },
  { "name": "André Onana", "position": "GK" },
  { "name": "Yann Sommer", "position": "GK" },
  { "name": "David Raya", "position": "GK" },
  { "name": "Giorgi Mamardashvili", "position": "GK" },
  { "name": "David de Gea", "position": "GK" },
  { "name": "Keylor Navas", "position": "GK" },
  { "name": "Edin Džeko", "position": "ST" },
  { "name": "Edinson Cavani", "position": "ST" },
  { "name": "Paulo Dybala", "position": "FW" },
  { "name": "Ángel Di María", "position": "RW" },
  { "name": "Neymar Jr.", "position": "LW" },
  { "name": "Richarlison", "position": "ST" },
  { "name": "Gabriel Martinelli", "position": "LW" },
  { "name": "Gabriel Jesus", "position": "ST" },
  { "name": "Endrick", "position": "ST" },
  { "name": "Estevão", "position": "RW" },
  { "name": "Arda Güler", "position": "RW/AM" },
  { "name": "Kenan Yıldız", "position": "LW" },
  { "name": "Francisco Conceição", "position": "RW" },
  { "name": "Pedro Neto", "position": "RW" },
  { "name": "Nuno Mendes", "position": "LB" },
  { "name": "Miguel Gutiérrez", "position": "LB" },
  { "name": "Federico Chiesa", "position": "RW" },
  { "name": "Matteo Retegui", "position": "ST" },
  { "name": "Santiago Giménez", "position": "ST" },
  { "name": "Evan Ferguson", "position": "ST" },
  { "name": "Jonathan David", "position": "ST" },
  { "name": "Yoane Wissa", "position": "FW" },
  { "name": "Bryan Mbeumo", "position": "RW" },
  { "name": "Marco Asensio", "position": "RW" },
  { "name": "Nicolás Otamendi", "position": "CB" },
  { "name": "John Stones", "position": "CB" },
  { "name": "Joško Gvardiol", "position": "CB/LB" },
  { "name": "Nathan Aké", "position": "CB/LB" },
  { "name": "Manuel Akanji", "position": "CB" },
  { "name": "Abdukodir Khusanov", "position": "CB" },
  { "name": "Nico O'Reilly", "position": "CM" },
  { "name": "Rayan Aït-Nouri", "position": "LB" },
  { "name": "Martín Zubimendi", "position": "DM" },
  { "name": "Cristhian Mosquera", "position": "CB" },
  { "name": "Eberechi Eze", "position": "AM" },
  { "name": "Noni Madueke", "position": "RW" },
  { "name": "Kepa Arrizabalaga", "position": "GK" },
  { "name": "Willian Pacho", "position": "CB" },
  { "name": "Lucas Beraldo", "position": "CB" },
  { "name": "Lucas Hernández", "position": "CB/LB" },
  { "name": "Vitinha", "position": "CM" },
  { "name": "Warren Zaïre-Emery", "position": "CM" },
  { "name": "Fabián Ruiz", "position": "CM" },
  { "name": "Bradley Barcola", "position": "LW" },
  { "name": "Désiré Doué", "position": "AM/W" },
  { "name": "Gonçalo Ramos", "position": "ST" },
  { "name": "David Alaba", "position": "CB/LB" },
  { "name": "Andriy Lunin", "position": "GK" },
  { "name": "Fran García", "position": "LB" },
  { "name": "Dean Huijsen", "position": "CB" },
  { "name": "Raúl Asencio", "position": "CB" },
  { "name": "Brahim Díaz", "position": "AM" },
  { "name": "Dani Ceballos", "position": "CM" },
  { "name": "Rodrygo", "position": "RW/LW" },
  { "name": "Gonzalo García", "position": "ST" },
  { "name": "Eric García", "position": "CB" },
  { "name": "Marc Casadó", "position": "DM" },
  { "name": "Fermín López", "position": "CM" },
  { "name": "Ferran Torres", "position": "FW" },
  { "name": "Kang-in Lee", "position": "AM/RW" },
  { "name": "Jurriën Timber", "position": "RB/CB" },
  { "name": "Ben White", "position": "RB/CB" },
  { "name": "Riccardo Calafiori", "position": "CB/LB" },
  { "name": "Oleksandr Zinchenko", "position": "LB/CM" },
  { "name": "Leandro Trossard", "position": "LW" },
  { "name": "Mikel Merino", "position": "CM" },
  { "name": "Myles Lewis-Skelly", "position": "CM/LB" },
  { "name": "Ethan Nwaneri", "position": "AM" },
  { "name": "Pelé", "position": "CF" },
  { "name": "Diego Maradona", "position": "AM" },
  { "name": "Johan Cruyff", "position": "CF" },
  { "name": "Franz Beckenbauer", "position": "CB" },
  { "name": "Alfredo Di Stéfano", "position": "FW" },
  { "name": "Ferenc Puskás", "position": "ST" },
  { "name": "George Best", "position": "RW" },
  { "name": "Eusébio", "position": "ST" },
  { "name": "Garrincha", "position": "RW" },
  { "name": "Lev Yashin", "position": "GK" },
  { "name": "Bobby Charlton", "position": "AM" },
  { "name": "Gerd Müller", "position": "ST" },
  { "name": "Paolo Rossi", "position": "ST" },
  { "name": "Gordon Banks", "position": "GK" },
  { "name": "Zico", "position": "AM" },
  { "name": "Sócrates", "position": "AM" },
  { "name": "Romário", "position": "ST" },
  { "name": "Ronaldo Nazário", "position": "ST" },
  { "name": "Ronaldinho", "position": "AM" },
  { "name": "Rivaldo", "position": "AM" },
  { "name": "Kaká", "position": "AM" },
  { "name": "Cafu", "position": "RB" },
  { "name": "Roberto Carlos", "position": "LB" },
  { "name": "Dida", "position": "GK" },
  { "name": "Lúcio", "position": "CB" },
  { "name": "Gilberto Silva", "position": "DM" },
  { "name": "Juninho Pernambucano", "position": "CM" },
  { "name": "Adriano", "position": "ST" },
  { "name": "Ronald Koeman", "position": "CB" },
  { "name": "Marco van Basten", "position": "ST" },
  { "name": "Ruud Gullit", "position": "AM" },
  { "name": "Frank Rijkaard", "position": "DM" },
  { "name": "Dennis Bergkamp", "position": "CF" },
  { "name": "Edwin van der Sar", "position": "GK" },
  { "name": "Clarence Seedorf", "position": "CM" },
  { "name": "Edgar Davids", "position": "CM" },
  { "name": "Robin van Persie", "position": "ST" },
  { "name": "Arjen Robben", "position": "RW" },
  { "name": "Wesley Sneijder", "position": "AM" },
  { "name": "Dirk Kuyt", "position": "FW" },
  { "name": "Patrick Kluivert", "position": "ST" },
  { "name": "David Beckham", "position": "RM" },
  { "name": "Paul Scholes", "position": "CM" },
  { "name": "Roy Keane", "position": "DM" },
  { "name": "Ryan Giggs", "position": "LW" },
  { "name": "Gary Neville", "position": "RB" },
  { "name": "Michael Owen", "position": "ST" },
  { "name": "Steven Gerrard", "position": "CM" },
  { "name": "Frank Lampard", "position": "CM" },
  { "name": "John Terry", "position": "CB" },
  { "name": "Ashley Cole", "position": "LB" },
  { "name": "Rio Ferdinand", "position": "CB" },
  { "name": "Nemanja Vidić", "position": "CB" },
  { "name": "Peter Čech", "position": "GK" },
  { "name": "Didier Drogba", "position": "ST" },
  { "name": "Yaya Touré", "position": "CM" },
  { "name": "Samuel Eto'o", "position": "ST" },
  { "name": "Michael Essien", "position": "CM" },
  { "name": "Claude Makélélé", "position": "DM" },
  { "name": "Thierry Henry", "position": "ST" },
  { "name": "Robert Pirès", "position": "LW" },
  { "name": "David Trezeguet", "position": "ST" },
  { "name": "Laurent Blanc", "position": "CB" },
  { "name": "Lilian Thuram", "position": "CB" },
  { "name": "Marcel Desailly", "position": "CB" },
  { "name": "Fabien Barthez", "position": "GK" },
  { "name": "Zinedine Zidane", "position": "AM" },
  { "name": "Eric Cantona", "position": "CF" },
  { "name": "Michel Platini", "position": "AM" },
  { "name": "Jean-Pierre Papin", "position": "ST" },
  { "name": "Andrea Pirlo", "position": "DM" },
  { "name": "Gianluigi Buffon", "position": "GK" },
  { "name": "Fabio Cannavaro", "position": "CB" },
  { "name": "Alessandro Nesta", "position": "CB" },
  { "name": "Paolo Maldini", "position": "CB" },
  { "name": "Franco Baresi", "position": "CB" },
  { "name": "Alessandro Del Piero", "position": "FW" },
  { "name": "Francesco Totti", "position": "AM" },
  { "name": "Filippo Inzaghi", "position": "ST" },
  { "name": "Christian Vieri", "position": "ST" },
  { "name": "Antonio Di Natale", "position": "FW" },
  { "name": "Gianfranco Zola", "position": "AM" },
  { "name": "Gennaro Gattuso", "position": "DM" },
  { "name": "Daniele De Rossi", "position": "DM" },
  { "name": "Giorgio Chiellini", "position": "CB" },
  { "name": "Leonardo Bonucci", "position": "CB" },
  { "name": "Gianluca Vialli", "position": "ST" },
  { "name": "Roberto Baggio", "position": "AM" },
  { "name": "Xabi Alonso", "position": "DM" },
  { "name": "Xavi", "position": "CM" },
  { "name": "Andrés Iniesta", "position": "CM" },
  { "name": "Cesc Fàbregas", "position": "CM" },
  { "name": "David Villa", "position": "ST" },
  { "name": "Fernando Torres", "position": "ST" },
  { "name": "Iker Casillas", "position": "GK" },
  { "name": "Carles Puyol", "position": "CB" },
  { "name": "Gerard Piqué", "position": "CB" },
  { "name": "Víctor Valdés", "position": "GK" },
  { "name": "David Silva", "position": "AM" },
  { "name": "Raúl", "position": "ST" },
  { "name": "Fernando Hierro", "position": "CB" },
  { "name": "Luis Enrique", "position": "CM" },
  { "name": "Juan Román Riquelme", "position": "AM" },
  { "name": "Pablo Aimar", "position": "AM" },
  { "name": "Gabriel Batistuta", "position": "ST" },
  { "name": "Javier Zanetti", "position": "RB" },
  { "name": "Hernán Crespo", "position": "ST" },
  { "name": "Juan Sebastián Verón", "position": "CM" },
  { "name": "Diego Simeone", "position": "DM" },
  { "name": "Mario Kempes", "position": "ST" },
  { "name": "Daniel Passarella", "position": "CB" },
  { "name": "Carlos Tévez", "position": "FW" },
  { "name": "Sergio Agüero", "position": "ST" },
  { "name": "Walter Samuel", "position": "CB" },
  { "name": "Roberto Ayala", "position": "CB" },
  { "name": "Diego Forlán", "position": "ST" },
  { "name": "Álvaro Recoba", "position": "FW" },
  { "name": "Iván Zamorano", "position": "ST" },
  { "name": "Marcelo Salas", "position": "ST" },
  { "name": "Carlos Valderrama", "position": "AM" },
  { "name": "René Higuita", "position": "GK" },
  { "name": "Faustino Asprilla", "position": "FW" },
  { "name": "Roger Milla", "position": "ST" },
  { "name": "Jay-Jay Okocha", "position": "AM" },
  { "name": "Nwankwo Kanu", "position": "FW" },
  { "name": "George Weah", "position": "ST" },
  { "name": "Lothar Matthäus", "position": "CM" },
  { "name": "Oliver Kahn", "position": "GK" },
  { "name": "Miroslav Klose", "position": "ST" },
  { "name": "Philipp Lahm", "position": "RB" },
  { "name": "Bastian Schweinsteiger", "position": "CM" },
  { "name": "Michael Ballack", "position": "CM" },
  { "name": "Jürgen Klinsmann", "position": "ST" },
  { "name": "Rudi Völler", "position": "ST" },
  { "name": "Oliver Bierhoff", "position": "ST" },
  { "name": "Mesut Özil", "position": "AM" },
  { "name": "Zlatan Ibrahimović", "position": "ST" },
  { "name": "Henrik Larsson", "position": "ST" },
  { "name": "Alan Shearer", "position": "ST" },
  { "name": "Gareth Bale", "position": "RW" },
  { "name": "Yassine Bounou (Bono)", "position": "GK" },
  { "name": "Nayef Aguerd", "position": "CB" },
  { "name": "Abderrazak Hamdallah", "position": "ST" },
  { "name": "Salem Al-Dawsari", "position": "LW" },
  { "name": "Akram Afif", "position": "LW" },
  { "name": "Hassan Al-Haydos", "position": "FW" },
  { "name": "Ali Maaloul", "position": "LB" },
  { "name": "Ferjani Sassi", "position": "CM" },
  { "name": "Youssef Msakni", "position": "LW" },
  { "name": "Wahbi Khazri", "position": "FW" },
  { "name": "Mostafa Mohamed", "position": "ST" },
  { "name": "Mahmoud Hassan \"Trezeguet\"", "position": "LW" },
  { "name": "Mohamed Elneny", "position": "DM" },
  { "name": "Ahmed Hegazi", "position": "CB" },
  { "name": "Tarek Hamed", "position": "DM" },
  { "name": "Saud Abdulhamid", "position": "RB" },
  { "name": "Mohammed Al-Owais", "position": "GK" },
  { "name": "Ali Al-Bulaihi", "position": "CB" },
  { "name": "Hassan Al-Tambakti", "position": "CB" },
  { "name": "Omar Al Somah", "position": "ST" },
  { "name": "Omar Abdulrahman", "position": "AM" },
  { "name": "Ali Mabkhout", "position": "ST" },
  { "name": "Ismail Matar", "position": "FW" },
  { "name": "Ali Al-Habsi", "position": "GK" },
  { "name": "Abdulkarim Hassan", "position": "LB" },
  { "name": "Boualem Khoukhi", "position": "CB" },
  { "name": "Karim Boudiaf", "position": "DM" },
  { "name": "Ahmed Khalil", "position": "ST" },
  { "name": "Younis Mahmoud", "position": "ST" },
  { "name": "Nashat Akram", "position": "CM" },
  { "name": "Ahmed Radhi", "position": "ST" },
  { "name": "Hussein Saeed", "position": "ST" },
  { "name": "Adnan Dirjal", "position": "CB" },
  { "name": "Noor Sabri", "position": "GK" },
  { "name": "Haider Abdul-Amir", "position": "CM" },
  { "name": "Mohammed Noor", "position": "CM" },
  { "name": "Sami Al-Jaber", "position": "ST" },
  { "name": "Majed Abdullah", "position": "ST" },
  { "name": "Yasser Al-Qahtani", "position": "ST" },
  { "name": "Nasser Al-Shamrani", "position": "ST" },
  { "name": "Mohamed Al-Deayea", "position": "GK" },
  { "name": "Mohamed Al-Shalhoub", "position": "AM" },
  { "name": "Saeed Al-Owairan", "position": "RW" },
  { "name": "Hossam Hassan", "position": "ST" },
  { "name": "Ibrahim Hassan", "position": "RB" },
  { "name": "Mohamed Aboutrika", "position": "AM" },
  { "name": "Essam El-Hadary", "position": "GK" },
  { "name": "Ahmed Hassan", "position": "CM" },
  { "name": "Wael Gomaa", "position": "CB" },
  { "name": "Emad Moteab", "position": "ST" },
  { "name": "Amr Zaki", "position": "ST" },
  { "name": "Mahmoud Al-Khatib", "position": "FW" },
  { "name": "Hassan Shehata", "position": "FW" },
  { "name": "Noureddine Naybet", "position": "CB" },
  { "name": "Mustapha Hadji", "position": "AM" },
  { "name": "Aziz Bouderbala", "position": "FW" },
  { "name": "Ahmed Faras", "position": "ST" },
  { "name": "Lakhdar Belloumi", "position": "AM" },
  { "name": "Rabah Madjer", "position": "ST" },
  { "name": "Riyad Boudebouz", "position": "AM" },
  { "name": "Baghdad Bounedjah", "position": "ST" },
  { "name": "Rebin Sulaka", "position": "CB" },
  { "name": "Ali Hussein Rahima", "position": "CB" },
  { "name": "Saad Natiq", "position": "CB" },
  { "name": "Zaid Tahseen", "position": "CB" },
  { "name": "Akam Hashim", "position": "CB" },
  { "name": "Joe Gomez", "position": "CB/RB" },
  { "name": "Joël Matip", "position": "CB" },
  { "name": "Thomas Vermaelen", "position": "CB" },
  { "name": "Vincent Kompany", "position": "CB" },
  { "name": "Malcom", "position": "RW" },
  { "name": "Alex Telles", "position": "LB" },
  { "name": "Samuel Umtiti", "position": "CB" }
];
